### ISSUE TITLE
x86_64-pc-linux-musl-ld.lld: error: unable to find library -lstdc++

### ISSUE THREAD

**Issue by elde-n** [rdbo/libmem#245]
NICE LIBRARY!

**Comment by rdbo** [comment]
Sounds like you don't have the standard C++ library installed. Install it however it is installed in your distro.
Also, there is no need for passive-agressive remarks like "NICE LIBRARY!". I don't owe you or anybody anything, I do this fully free work simply because I want to, not because I have to.
What you could've said instead is
"""
Hey, I'm new to this library and I'm not being able to compile it. I'm trying to use it with [Rust | C/C++ | Python], on version 5.0.0 and this is the compilation error:
  error: x86_64-pc-linux-musl-ld.lld: error: unable to find library -lstdc++
My Linux distro is [ INSERT DISTRO HERE ]
"""
which would've made it easier to help you with your issue
